# Generated by Django 4.2.7 on 2023-12-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
