# Generated by Django 4.2.7 on 2023-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_be_ordered',
            field=models.BooleanField(default=True, verbose_name='Можно заказать'),
        ),
    ]
